context.modules = [
{   name = libpipewire-module-filter-chain
    args = {
        node.description = "Barracuda EQ"
        media.name       = "Barracuda EQ"
        filter.graph = {
            nodes = [
        { type = builtin label = bq_lowshelf name = eq0 control = { "Freq" = 31 "Q" = 1.0 "Gain" = 5.0 } }
        { type = builtin label = bq_peaking name = eq1 control = { "Freq" = 63 "Q" = 1.4 "Gain" = -4.0 } }
        { type = builtin label = bq_peaking name = eq2 control = { "Freq" = 125 "Q" = 1.4 "Gain" = -4.0 } }
        { type = builtin label = bq_peaking name = eq3 control = { "Freq" = 250 "Q" = 1.4 "Gain" = -2.0 } }
        { type = builtin label = bq_peaking name = eq4 control = { "Freq" = 500 "Q" = 1.4 "Gain" = 0.0 } }
        { type = builtin label = bq_peaking name = eq5 control = { "Freq" = 1000 "Q" = 1.4 "Gain" = 2.0 } }
        { type = builtin label = bq_peaking name = eq6 control = { "Freq" = 2000 "Q" = 1.4 "Gain" = 5.0 } }
        { type = builtin label = bq_peaking name = eq7 control = { "Freq" = 4000 "Q" = 1.4 "Gain" = 6.0 } }
        { type = builtin label = bq_peaking name = eq8 control = { "Freq" = 8000 "Q" = 1.4 "Gain" = 4.0 } }
        { type = builtin label = bq_highshelf name = eq9 control = { "Freq" = 16000 "Q" = 1.0 "Gain" = 2.0 } }
            ]
            links = [
        { output = "eq0:Out" input = "eq1:In" }
        { output = "eq1:Out" input = "eq2:In" }
        { output = "eq2:Out" input = "eq3:In" }
        { output = "eq3:Out" input = "eq4:In" }
        { output = "eq4:Out" input = "eq5:In" }
        { output = "eq5:Out" input = "eq6:In" }
        { output = "eq6:Out" input = "eq7:In" }
        { output = "eq7:Out" input = "eq8:In" }
        { output = "eq8:Out" input = "eq9:In" }
            ]
            inputs  = [ "eq0:In" ]
            outputs = [ "eq9:Out" ]
        }
        audio.channels = 2
        audio.position = [ FL FR ]
        capture.props  = { node.name = "barracuda_eq"  media.class = Audio/Sink  node.description = "Barracuda EQ" }
        playback.props = { node.name = "barracuda_eq_out"  node.passive = true  node.target = "alsa_output.usb-Macronix_Razer_Barracuda_2.4_XXXX-00.analog-stereo" }
    }
}
]
